# Generated by Django 3.2.3 on 2021-07-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_is_active'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_recipients', to='characters.Character'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_author', to='characters.character'),
        ),
    ]
