# Generated by Django 3.2.3 on 2022-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(choices=[('Deplacement', 'Deplacement'), ('Dialogue', 'Dialogue'), ('Combat', 'Combat'), ('Combat Spacial', 'Combat Sp')], max_length=50),
        ),
    ]
