# Generated by Django 3.2.3 on 2022-02-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventtype_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterEvent',
        ),
    ]
