# Generated by Django 3.2.3 on 2021-06-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
        ('characters', '0002_alter_character_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='characters'),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='character',
            name='situation',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='locations.situation'),
        ),
        migrations.AlterField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
