# Generated by Django 3.2.3 on 2021-06-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('characters', '0003_auto_20210605_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.situation'),
        ),
    ]
