# Generated by Django 3.2.3 on 2021-07-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
