# Generated by Django 3.2.3 on 2022-02-19 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='characters.character')),
                ('power', models.PositiveIntegerField()),
                ('science', models.PositiveIntegerField()),
                ('dexterity', models.PositiveIntegerField()),
                ('persuasion', models.PositiveIntegerField()),
                ('politics', models.PositiveIntegerField()),
                ('navigation', models.PositiveIntegerField()),
                ('repairs', models.PositiveIntegerField()),
                ('demolition', models.PositiveIntegerField()),
                ('perception', models.PositiveIntegerField()),
                ('force', models.PositiveIntegerField()),
            ],
        ),
    ]
