# Generated by Django 3.2.3 on 2022-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='piloting',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
