# Generated by Django 3.2.3 on 2022-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_attributes_piloting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='demolition',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='dexterity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='force',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='navigation',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='perception',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='persuasion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='piloting',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='politics',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='power',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='repairs',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='science',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
