# Generated by Django 3.2.3 on 2022-02-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20220220_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='power_oto',
        ),
        migrations.AddField(
            model_name='powerattr',
            name='attributes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.attributes'),
        ),
    ]
