# Generated by Django 3.2.3 on 2022-02-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_demolitionattribute_dexterityattribute_forceattribute_navigationattribute_perceptionattribute_persua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demolition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('traps', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('explosives', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Dexterity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('firing', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('throwing', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('jetpack', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('dodge', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('parade', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('confusion', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('compulsion', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('telekenisis', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('athleticism', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('lightsaber', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('focus', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('psychic_protection', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('shields', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('artillery', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('sensors', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('astronavigation', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('astronomy', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Perception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('search', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('clues', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('hear_rumor', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('detect_trap', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('scouting', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Persuasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('intimidation', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('command', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('charisma', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('seduction', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Piloting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('lasers', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('missiles', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('control', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('dodge', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('tactics', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('adaptation', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Politics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('take_position', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('contest_position', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('start_rumor', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('bribe', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('poise', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('scheming', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('cultures', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('promotion', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('hand_to_hand', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('melee', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('heavy_weapons', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('vigor', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('ships', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('droids', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('comms', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('system_d', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('tactics', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('jamming', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('medicine', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('bacta', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('cybernetics', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('survival', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('xenobiology', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('critical', models.PositiveIntegerField(blank=True, default=3, null=True)),
                ('character', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.RemoveField(
            model_name='dexterityattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='forceattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='navigationattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='perceptionattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='persuasionattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='pilotingattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='politicsattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='powerattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='repairattribute',
            name='character',
        ),
        migrations.RemoveField(
            model_name='scienceattribute',
            name='character',
        ),
        migrations.DeleteModel(
            name='DemolitionAttribute',
        ),
        migrations.DeleteModel(
            name='DexterityAttribute',
        ),
        migrations.DeleteModel(
            name='ForceAttribute',
        ),
        migrations.DeleteModel(
            name='NavigationAttribute',
        ),
        migrations.DeleteModel(
            name='PerceptionAttribute',
        ),
        migrations.DeleteModel(
            name='PersuasionAttribute',
        ),
        migrations.DeleteModel(
            name='PilotingAttribute',
        ),
        migrations.DeleteModel(
            name='PoliticsAttribute',
        ),
        migrations.DeleteModel(
            name='PowerAttribute',
        ),
        migrations.DeleteModel(
            name='RepairAttribute',
        ),
        migrations.DeleteModel(
            name='ScienceAttribute',
        ),
    ]
