# Generated by Django 3.2.3 on 2022-02-20 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0013_auto_20220220_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='value',
            field=models.PositiveIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(3)]),
        ),
    ]
