# Generated by Django 3.2.3 on 2022-02-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_auto_20220220_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='hand_to_hand',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='heavy_weapons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='melee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='vigor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
