# Generated by Django 3.2.3 on 2021-05-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='locations')),
                ('description', models.TextField(max_length=2000)),
                ('display_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='situations')),
                ('description', models.TextField(max_length=500)),
                ('display_rank', models.IntegerField(default=0)),
                ('location', models.ForeignKey(default='void', on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_reversible', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(default='void', on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='locations.location')),
                ('origin', models.ForeignKey(default='void', on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='locations.location')),
            ],
        ),
    ]
