# Generated by Django 3.2.3 on 2022-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='image_url',
        ),
    ]
